[DEFAULT]
point_cloud_path = ./data/gt_armadillo.xyz
experiment_name  = rcg_armadillo
logging_root     = ../logs
gpu              = 0
num_workers      = 0

# Training loop
num_steps        = 200000
steps_til_summary= 1000
steps_til_ckpt   = 50000
ckpt_step        = 0
num_pts_on       = 10000

# Network
hidden_size      = 256
hidden_layers    = 3

# BLA defaults
init_t           = 1.0
init_beta        = 0.05
init_zeta        = 1.0
sigma            = 30.0
trainable        = True
